es_name: "PGPE"
es_config:
  pop_size: 64
  center_learning_rate: 0.006
  stdev_learning_rate: 0.089
  init_stdev: 0.039
  optimizer: "adam"
hidden_size: 100
batch_size: 1024
max_iter: 5000
test_interval: 1000
log_interval: 100
seed: 42
gpu_id: [0, 1, 2, 3]
debug: false