es_name: "PGPE"
es_config:
  center_learning_rate: 0.011
  stdev_learning_rate: 0.054
  init_stdev: 0.095
  optimizer: "adam"
hidden_size: 100
num_tests: 100
n_repeats: 64
max_iter: 2000
test_interval: 100
log_interval: 10
seed: 42
gpu_id: [0, 1, 2, 3]
debug: false